[package]
name = "libfaad2-rs"
version = "0.0.0"
authors = ["Charlie Somerville <charlie@charlie.bz>"]
edition = "2018"

[dependencies]
libfaad2-sys = { path = "libfaad2-sys" }

# [build-dependencies]
# bindgen = "0.53"
